server:
  port: ${EXECUTOR_PORT:8082}

spring:
  application:
    name: ruleforge-executor

ruleforge:
  knowledgeUpdateCycleV2: 300
  isKnowledgeUpdateRemoteV2: true
  console:
    url: ${CONSOLE_URL:http://localhost:8081}
